import './screens/utils.js'
import './screens/register.js'
import './components/header.js'
import './components/createPost.js'
import './components/listPost.js'
import './components/postItem.js'
import './components/inputWrapper.js'
import './screens/story.js'
import './navigo.js'
export function redirect(){}
